// filepath: BibleAppPOCV2/Views/VerseSummaryPopupView.swift
import SwiftUI

struct VerseSummaryPopupView: View {
    let summary: VerseSummary
    let onClose: () -> Void
    @StateObject private var viewModel = VerseSummaryViewModel()

    var body: some View {
        VStack(spacing: 12) {
            // Grab Handle
            RoundedRectangle(cornerRadius: 2)
                .frame(width: 40, height: 5)
                .foregroundStyle(.secondary)
                .padding(.top, 10)

            // Header
            Text("\(summary.reference) Summary")
                .font(.title2.bold())
                .multilineTextAlignment(.center)

            Divider()

            // Summary Content
            ScrollView {
                VStack(alignment: .leading, spacing: 12) {
                    if viewModel.isLoading {
                        HStack {
                            ProgressView()
                                .scaleEffect(0.8)
                            Text("Generating AI summary...")
                                .font(.body)
                                .foregroundStyle(.secondary)
                        }
                        .frame(maxWidth: .infinity, alignment: .center)
                        .padding()
                    } else if !viewModel.errorMessage.isEmpty {
                        VStack(alignment: .leading, spacing: 8) {
                            Label("Error", systemImage: "exclamationmark.triangle")
                                .font(.headline)
                                .foregroundStyle(.red)
                            
                            Text(viewModel.errorMessage)
                                .font(.body)
                                .foregroundStyle(.secondary)
                        }
                        .padding()
                        .background(.red.opacity(0.1))
                        .cornerRadius(8)
                    } else {
                        Text(viewModel.summaryText.isEmpty ? "No summary available" : viewModel.summaryText)
                            .font(.body)
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                }
                .padding(.horizontal)
            }

            Divider()

            // Metadata
            VStack(spacing: 4) {
                if let version = summary.modelVersion {
                    Text("Generated by: \(version)")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                
                Text("BART Bible AI Model")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }

            // Close Button
            Button(action: onClose) {
                Label("Close", systemImage: "xmark.circle.fill")
                    .font(.headline)
                    .padding(.vertical, 10)
                    .frame(maxWidth: .infinity)
            }
            .buttonStyle(.borderedProminent)
            .padding(.horizontal)
            .padding(.bottom, 20)
        }
        .padding(.top, 4)
        .background(.background)
        .cornerRadius(16)
        .shadow(radius: 10)
        .frame(maxHeight: .infinity, alignment: .bottom)
        .transition(.move(edge: .bottom))
        .accessibilityElement(children: .contain)
        .onAppear {
            viewModel.summarize(verse: summary.summaryText)
        }
    }
}
