// filepath: BibleAppPOCV2/Views/VerseSummaryPopupView.swift
import SwiftUI

struct VerseSummaryPopupView: View {
    let summary: VerseSummary
    let onClose: () -> Void
    @StateObject private var viewModel: VerseSummaryViewModel

    init(summary: VerseSummary, onClose: @escaping () -> Void) {
        self.summary = summary
        self.onClose = onClose
        // Shared instance preserves readiness state across popups
        self._viewModel = StateObject(wrappedValue: VerseSummaryViewModel.shared)
    }

    var body: some View {
        VStack(spacing: 12) {
            // Grab Handle
            RoundedRectangle(cornerRadius: 2)
                .frame(width: 40, height: 5)
                .foregroundStyle(.secondary)
                .padding(.top, 10)

            // Header
            Text("\(summary.reference) AI Commentary")
                .font(.title2.bold())
                .multilineTextAlignment(.center)

            Divider()

            // Content
            ScrollView {
                VStack(alignment: .leading, spacing: 16) {
                    if viewModel.isLoading {
                        loadingView(text: "Generating AI commentary...")
                    } else if !viewModel.modelAvailable {
                        loadingView(text: "Loading Core ML model...")
                    } else if !viewModel.errorMessage.isEmpty {
                        errorView(message: viewModel.errorMessage)
                    } else {
                        commentarySection
                        devotionalSection
                        if viewModel.commentaryText.isEmpty &&
                           viewModel.devotionalText.isEmpty {
                            Text("No commentary available")
                                .font(.body)
                                .foregroundStyle(.secondary)
                                .frame(maxWidth: .infinity, alignment: .center)
                                .padding()
                        }
                    }
                }
                .padding(.horizontal)
            }

            Divider()

            // Metadata
            VStack(spacing: 4) {
                if let version = summary.modelVersion {
                    Text("Generated by: \(version)")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                Text(viewModel.modelVersion)
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .padding(.horizontal, 8)
                    .padding(.vertical, 2)
                    .background(.blue.opacity(0.1))
                    .cornerRadius(4)

                Text(viewModel.getSummarizerStatus())
                    .font(.caption2)
                    .foregroundStyle(.tertiary)
            }

            // Close Button
            Button(action: onClose) {
                Label("Close", systemImage: "xmark.circle.fill")
                    .font(.headline)
                    .padding(.vertical, 10)
                    .frame(maxWidth: .infinity)
            }
            .buttonStyle(.borderedProminent)
            .padding(.horizontal)
            .padding(.bottom, 20)
        }
        .padding(.top, 4)
        .background(.background)
        .cornerRadius(16)
        .shadow(radius: 10)
        .frame(maxHeight: .infinity, alignment: .bottom)
        .transition(.move(edge: .bottom))
        .accessibilityElement(children: .contain)
        .task {
            await viewModel.summarize(verse: summary.summaryText)
        }
    }

    // MARK: - Subviews

    @ViewBuilder private func loadingView(text: String) -> some View {
        HStack {
            ProgressView().scaleEffect(0.8)
            Text(text).font(.body).foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity, alignment: .center)
        .padding()
    }

    @ViewBuilder private func errorView(message: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Label("Error", systemImage: "exclamationmark.triangle")
                .font(.headline)
                .foregroundStyle(.red)

            Text(message)
                .font(.body)
                .foregroundStyle(.secondary)

            Button("Retry") { viewModel.retryInitialization() }
                .buttonStyle(.bordered)
        }
        .padding()
        .background(.red.opacity(0.1))
        .cornerRadius(8)
    }

    @ViewBuilder private var commentarySection: some View {
        if !viewModel.commentaryText.isEmpty {
            VStack(alignment: .leading, spacing: 8) {
                Label("Commentary", systemImage: "text.book.closed")
                    .font(.headline)
                    .foregroundStyle(.primary)

                Text(viewModel.commentaryText)
                    .font(.body)
                    .frame(maxWidth: .infinity, alignment: .leading)
            }
            .padding()
            .background(.blue.opacity(0.05))
            .cornerRadius(8)
        }
    }

    @ViewBuilder private var devotionalSection: some View {
        if !viewModel.devotionalText.isEmpty {
            VStack(alignment: .leading, spacing: 8) {
                Label("Devotional", systemImage: "heart")
                    .font(.headline)
                    .foregroundStyle(.primary)

                Text(viewModel.devotionalText)
                    .font(.body)
                    .frame(maxWidth: .infinity, alignment: .leading)
            }
            .padding()
            .background(.green.opacity(0.05))
            .cornerRadius(8)
        }
    }
}
