// filepath: BibleAppPOCV2/Views/VerseSummaryPopupView.swift
import SwiftUI

struct VerseSummaryPopupView: View {
    let summary: VerseSummary
    let onClose: () -> Void
    @StateObject private var viewModel = VerseSummaryViewModel()

    var body: some View {
        VStack(spacing: 12) {
            // Grab Handle
            RoundedRectangle(cornerRadius: 2)
                .frame(width: 40, height: 5)
                .foregroundStyle(.secondary)
                .padding(.top, 10)

            // Header
            Text("\(summary.reference) Summary")
                .font(.title2.bold())
                .multilineTextAlignment(.center)

            Divider()

            // Summary Text
            ScrollView {
                Text(viewModel.summaryText.isEmpty ? "Generating summary..." : viewModel.summaryText)
                    .font(.body)
                    .padding(.horizontal)
                    .frame(maxWidth: .infinity, alignment: .leading)
// File: BibleAppPOCV2/Views/VerseSummaryPopupView.swift
// Directory: Views
// Purpose: Display the summarized verse result in the popup view
            }

// TODO: Update this view to render the summary result from VerseSummaryViewModel
            Divider()

            // Metadata (Optional)
            if let version = summary.modelVersion {
                Text("Generated by: \(version)")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }

            // Close Button
            Button(action: onClose) {
                Label("Close", systemImage: "xmark.circle.fill")
                    .font(.headline)
                    .padding(.vertical, 10)
                    .frame(maxWidth: .infinity)
            }
            .buttonStyle(.borderedProminent)
            .padding(.horizontal)
            .padding(.bottom, 20)
        }
        .padding(.top, 4)
        .background(.background)
        .cornerRadius(16)
        .shadow(radius: 10)
        .frame(maxHeight: .infinity, alignment: .bottom)
        .transition(.move(edge: .bottom))
        .accessibilityElement(children: .contain)
        .onAppear {
            viewModel.summarize(verse: summary.summaryText)
        }
    }
}
